ALTER TABLE "Creator"
ADD COLUMN "profileImageUrl" TEXT,
ADD COLUMN "nextAction" TEXT,
ADD COLUMN "lastContactedAt" TIMESTAMP(3),
ADD COLUMN "nextFollowUpAt" TIMESTAMP(3),
ADD COLUMN "visualFitScore" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "commercialFitScore" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "trustPurchaseIntentScore" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "overallScoreOverride" DOUBLE PRECISION,
ADD COLUMN "isDemo" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Task"
ADD COLUMN "isDemo" BOOLEAN NOT NULL DEFAULT false;
